from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(560, 20, 211, 41))
        self.btnSave.setObjectName("btnSave")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(560, 70, 211, 41))
        self.btnDelete.setObjectName("btnDelete")
        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(560, 120, 211, 41))
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnList = QtWidgets.QPushButton(self.centralwidget)
        self.btnList.setGeometry(QtCore.QRect(560, 170, 211, 41))
        self.btnList.setObjectName("btnList")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(220, 20, 311, 41))
        self.txtID.setObjectName("txtID")
        self.txtFirstname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFirstname.setGeometry(QtCore.QRect(220, 70, 311, 41))
        self.txtFirstname.setObjectName("txtFirstname")
        self.txtLastname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLastname.setGeometry(QtCore.QRect(220, 120, 311, 41))
        self.txtLastname.setObjectName("txtLastname")
        self.txtCity = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCity.setGeometry(QtCore.QRect(220, 170, 311, 41))
        self.txtCity.setObjectName("txtCity")
        self.txtPhone = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPhone.setGeometry(QtCore.QRect(220, 220, 311, 41))
        self.txtPhone.setObjectName("txtPhone")
        self.txtEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(220, 270, 311, 41))
        self.txtEmail.setObjectName("txtEmail")
        self.lblID = QtWidgets.QLabel(self.centralwidget)
        self.lblID.setGeometry(QtCore.QRect(10, 20, 201, 41))
        self.lblID.setObjectName("lblID")
        self.lblFirstname = QtWidgets.QLabel(self.centralwidget)
        self.lblFirstname.setGeometry(QtCore.QRect(10, 70, 201, 41))
        self.lblFirstname.setObjectName("lblFirstname")
        self.lblLastname = QtWidgets.QLabel(self.centralwidget)
        self.lblLastname.setGeometry(QtCore.QRect(10, 120, 201, 41))
        self.lblLastname.setObjectName("lblLastname")
        self.lblCity = QtWidgets.QLabel(self.centralwidget)
        self.lblCity.setGeometry(QtCore.QRect(10, 170, 201, 41))
        self.lblCity.setObjectName("lblCity")
        self.lblPhone = QtWidgets.QLabel(self.centralwidget)
        self.lblPhone.setGeometry(QtCore.QRect(10, 220, 201, 41))
        self.lblPhone.setObjectName("lblPhone")
        self.lblEmail = QtWidgets.QLabel(self.centralwidget)
        self.lblEmail.setGeometry(QtCore.QRect(10, 270, 201, 41))
        self.lblEmail.setObjectName("lblEmail")
        self.tblList = QtWidgets.QTableWidget(self.centralwidget)
        self.tblList.setGeometry(QtCore.QRect(10, 330, 891, 341))
        self.tblList.setObjectName("tblList")
        self.tblList.setColumnCount(0)
        self.tblList.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.btnDelete.setText(_translate("MainWindow", "Delete"))
        self.btnUpdate.setText(_translate("MainWindow", "Update"))
        self.btnList.setText(_translate("MainWindow", "List"))
        self.lblID.setText(_translate("MainWindow", "ID"))
        self.lblFirstname.setText(_translate("MainWindow", "Firstname"))
        self.lblLastname.setText(_translate("MainWindow", "Lastname"))
        self.lblCity.setText(_translate("MainWindow", "City"))
        self.lblPhone.setText(_translate("MainWindow", "Phone"))
        self.lblEmail.setText(_translate("MainWindow", "Email"))
